# Generated by Django 3.0.8 on 2021-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='replay',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
